# Generated by Django 5.1.3 on 2024-11-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название монеты')),
                ('symbol', models.CharField(max_length=10, unique=True, verbose_name='Символ монеты')),
                ('api_url', models.URLField(verbose_name='URL API для курса')),
            ],
            options={
                'verbose_name': 'Монета',
                'verbose_name_plural': 'Монеты',
            },
        ),
    ]
