# Generated by Django 5.1.3 on 2024-11-07 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Количество')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coins', to='coins.coin', verbose_name='ID Монеты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coins', to=settings.AUTH_USER_MODEL, verbose_name='ID Пользователя')),
            ],
            options={
                'verbose_name': 'Пользовательские накполения',
            },
        ),
    ]
