# Generated by Django 5.1.3 on 2024-11-08 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_usercoin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='api_url',
        ),
    ]
